spring:
  # 选择加载不同环境的配置文件
  profiles:
    active: dev

  # 页面方面的配置
  thymeleaf:
    encoding: UTF-8
    # 热部署静态文件
    cache : false

  # 数据方面的配置
  datasource:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 配置监控统计拦截的filters
        filters: stat
        # 连接池的配置信息
        maxActive: 20
        initialSize: 5
        minIdle: 5
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.linkinstars.springBootTemplate.bean

pagehelper:
    helperDialect: mysql