spring:
  # 选择加载不同环境的配置文件
  profiles:
    active: dev
    include: mvc, data, config

  # 配置热部署
  devtools:
    restart:
      # 如果改为true则当修改java目录下的文件时会自动进行重启
      enabled: false
      additional-paths: src/main/java

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.linkinstars.springBootTemplate.bean

pagehelper:
    helperDialect: mysql